### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by lalit9819** [DhananjaiH/MeasureCam#1]
at com.example.cameraFocus.CameraFocusActivity.surfaceChanged(CameraFocusActivity.java:607)

**Comment by DhananjaiH** [comment]
Hi @lalit9819, this is a very old project, and I think the target API was set at Gingerbread. It has not been updated since. If you would like to collaborate on this project and bring it up to speed on the latest APIs, would be happy to have your help on this.

**Comment by 6ar9** [comment]
@lalit9819, to make it work (tested on Android 5.0.2):

For the problem to which you refer, 
1) comment line 606
2) add before line 607:
List<Camera.Size> previewSizes = p.getSupportedPreviewSizes();
Camera.Size previewSize = previewSizes.get(0);
p.setPreviewSize(previewSize.width, previewSize.height);

///////////////////////
Also, for compatibility with the formatting of non-US decimal systems, change line 66 from:
DecimalFormat ThreeDForm = new DecimalFormat("#.###");
to:
DecimalFormat ThreeDForm;

and add inside onCreate:
DecimalFormatSymbols otherSymbols = new DecimalFormatSymbols(getResources().getConfiguration().locale);
otherSymbols.setDecimalSeparator('.');
ThreeDForm = new DecimalFormat("#.###", otherSymbols);

/////////////////////////////
A minor issue:
in line 575,  logging tag too long; change:
Log.v("on user leave hint pressed", "on userlevve hint pressesd");
for:
Log.v(TAG, "on user leave hint pressed");

//////////////////////
Finally, if you adopt the gradle folder system:
line 389, change:
getMenuInflater().inflate(R.layout.menu, menu);
for:
getMenuInflater().inflate(R.menu.menu, menu);

////////////////////
The mayor issue, anyway, would be to switch from "Camera" to "Camera2" api.

**Comment by DhananjaiH** [comment]
Thank you @6ar9 for providing the solution to the above issue. Marking the issue as closed.
