### ISSUE TITLE
Length?

### ISSUE THREAD

**Issue by 6ar9** [DhananjaiH/MeasureCam#2]
@DhananjaiH, nice and clean code!!

A couple of questions:

1) Distance and height work very well, the length seems to me that it is not accurate at all...
Maybe I'm doing something wrong, although actually I follow your instructions... Does the tilt of the phone matters (i.e., pointing to the base of the object or pointing at the same height of the camera)?

Anyway, what method do you use?
I wonder if you could calculate the chord of an arc (-> the length of measured object) knowing the angle from the center (-> from camera position) and the distance from the center to the chord (-> the distance calculated by your method), but trigonometry is not my field at all... are you using this approach when you write "theta * D"?

2) What kind of license does it have? Can I use relevant parts of this code in a commercial app?
It would not be an application focused on camera measurements: this feature would be a minor and experimental addition to an archeology application.

Thanks

**Comment by DhananjaiH** [comment]
Hi @6ar9,

Sorry for the late response.

1. As embarrassing as this is for me to admit, I do not actually recollect why I chose that particular approach for calculating length. I should give you a heads-up though: I believe I have used the raw accelerometer values from whatever model of phone I used back then. There are some fallbacks of using this approach. 
    (a) There is usually a lot of RMS noise in accelerometer readings, even in their best sensitivity modes. You can clean this up a little by using a simple [Lowpass Filter](https://en.wikipedia.org/wiki/Low-pass_filter) on the incoming data (it will give you a slightly more stable reading).
    (b) A majority of the newer phones have 6-axis IMUs (Inertial Motion Units) which have an Accelerometer and Gyroscope. You could perform some sensor fusion get an a fairly accurate tilt/orientation of the phones, that would help in getting better accuracy in your measurements. There some very basic formulae for getting the tilt angle on each of the three axes.
    (c) Finally, when using the accelerometer readings, you also need to take care to eliminate the gravitational acceleration on the vertical axis, which can severely affect the measurements taken using the vertical axis.

2. I just added an MIT license file to the repo. Feel free to use it in your application if you find it useful. A simple acknowledgement in your work would be nice! 😃 

I hope this information is of use to you. Thanks.

**Comment by 6ar9** [comment]
@DhananjaiH, thank you for the exhaustive answer!
And for including the license.

I need to digest the information you gave me ... and maybe I'll try to do some experiment.
If in the future I will update to your code, I will inform you. And so I will warn you if I publish my software with the inclusion of your code too.

Best regards
